### ISSUE TITLE
Make possible to add attachments and images in a easy way

### ISSUE THREAD

**Issue by gabrielalmeidaa** [claudiosegala/playbook-centeias#5]
Add the possibility for the user to upload files to the system. Consider using AWS for storage.

**Comment by claudiosegala** [comment]
This enhancement can be delayed to the second release (mid-November) because it won't affect the initial user experience. But we should talk to Marcela to build workarounds. @CrimsonCrown please talk to Marcela and discover a way to at least use images on the markdown. I think that maybe you could use Zottero to store the images and use the link to display in markdown. If you find a solution, write on the Getting Stated page.

**Comment by claudiosegala** [comment]
File uploading wont be necessary, but we need documentation on how to use OwnCloud to add images in the system

**Comment by claudiosegala** [comment]
To add image using ownCloud, it is simple!
Share the image publicly, open link and click with the right button in the image. Then copy address and use this link to reference in the markdown.

**Comment by claudiosegala** [comment]
- [x] Need to add documentation explaining how to add an image
- [x] Add POPs images in [this onwCloud folder](https://cloud.centeias.net/index.php/apps/files/?dir=/Sala%20de%20Situa%C3%A7%C3%A3o/Centeias%20DATA&fileid=41398)
